security:
    password_hashers:
        App\Entity\AppUser:
            algorithm: auto

    providers:
        entity_provider:
            entity:
                class: App\Entity\AppUser
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login_check
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
        admin:
            lazy: true
            provider: entity_provider
            form_login:
                default_target_path: /chat/messages/
                login_path: /admin/login
                check_path: /admin/login
                enable_csrf: true
            logout:
                path: admin_logout
                target: /admin/login

    role_hierarchy:
        ROLE_ADMINISTRATOR: ROLE_MODERATOR
        ROLE_MODERATOR: [ROLE_ORGANIZER, ROLE_ARTIST]
        ROLE_ORGANIZER: ROLE_SPECTATOR
        ROLE_ARTIST: ROLE_SPECTATOR

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/registration, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/searchByEmail, roles: PUBLIC_ACCESS }
        - { path: ^/api/searchByUsername, roles: PUBLIC_ACCESS }
        - { path: ^/api/me$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/appusers, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/events/create, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/events/.+/(update|delete|participate|comments), roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/places/create, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/places/.+/(update|comments|delete), roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/chat/messages, roles: [ROLE_ORGANIZER, ROLE_ARTIST, ROLE_ADMINISTRATOR] }
        - { path: ^/admin, roles: ROLE_ADMINISTRATOR }
